_id: ae8d9b60-4d15-11eb-add5-6fac998eab2b
replying_to: '1609593478'
slug: home-automation-setup-docker-compose
name: Adam Sherman
email: 50bbab198767f0dae3f493acf36a76f4
message: "Yeah, other than the restrictions of using an iframe, that looks good. Thanks!\r\n\r\nDo you know if that is how the supported Home Assistant setup works?"
id: 1609604108
date: '2021-01-02T16:15:08.670Z'
