_id: fd48b930-4d31-11eb-a754-4fb3cfc7b3d5
replying_to: '1609604108'
slug: home-automation-setup-docker-compose
name: Wouter Bulten
email: 95be418a0d147888e2ba0f2ad7c1f4b2
message: >-
  Hi Adam, you mean if you run the Home Assistant OS? I'm not completely sure as
  I don't have experience with that setup, but I imagine it's at least something
  similar.
id: 1609616266
date: '2021-01-02T19:37:46.683Z'
