_id: ee459820-4cfc-11eb-8ba3-ad359a80fbf7
replying_to: '1609572597'
slug: home-automation-setup-docker-compose
name: Wouter Bulten
email: 95be418a0d147888e2ba0f2ad7c1f4b2
message: "Hi Adam, thanks!\r\n\r\nWould this be something you are looking for? https://www.home-assistant.io/integrations/panel_iframe/ Then you can add your Node-RED instance to the sidebar.\r\n\r\nRegards, Wouter"
id: 1609593478
date: '2021-01-02T13:17:58.277Z'
