_id: 17beb240-3bcd-11eb-9778-b15bde2adb43
replying_to: ''
slug: home-automation-setup-docker-compose
name: René
email: 3a2491f34be653355aa076e4f82572b5
message: "Hello Wouter,\r\n\r\nWhat a great tutorial which i also will try to setup!!\r\nRunning Domoticz on a pi3B at the moment, but also looking for more\r\npower."
id: 1607703762
date: '2020-12-11T16:22:42.181Z'
