_id: 0c6ea250-54ab-11eb-9dd6-859abf416902
replying_to: '1610412718'
slug: home-automation-setup-docker-compose
name: Wouter Bulten
email: 95be418a0d147888e2ba0f2ad7c1f4b2
message: "Hi Kiat,\r\n\r\nThanks for the compliments. I've been traversing a similar path: from a single Pi using 2 lightbulbs to a more elaborate system using Docker. Great to hear that the guide helped!\r\n\r\nRegards, Wouter"
id: 1610437919
date: '2021-01-12T07:51:59.291Z'
