_id: a2e33710-4d34-11eb-a754-4fb3cfc7b3d5
replying_to: '1609616266'
slug: home-automation-setup-docker-compose
name: Adam Sherman
email: 50bbab198767f0dae3f493acf36a76f4
message: "I got it working. Figuring out how to get things to proxy is a project on the list, then.\r\n\r\nThanks for your help!"
id: 1609617403
date: '2021-01-02T19:56:43.448Z'
