_id: 508f6580-1038-11eb-aeda-c939621d6ca9
replying_to: '1602858090'
slug: home-automation-setup-docker-compose
name: Pablo
email: c517ce730309a6472d6c363f4e76acbf
message: "Hi Wouter,\r\n\r\nFinally was able to set everything up. I went with Home Assistant Cloud, on the trial right now, and it's working great with the Companion App. I'll definitely upgrade after the trial is over. Rather pay for this option than opening ports in my router. Also, it is a convenient way to support the community. Thanks again, really appreciate your help!"
id: 1602911962
date: '2020-10-17T05:19:22.461Z'
